#spring.application.name=greenledger
server.port=8080
server.address=0.0.0.0
spring.data.mongodb.uri=mongodb+srv://greenledger22_db_user:P5uOJYAEFzQqWCsN@cluster0.od8ro7c.mongodb.net/sustainability?appName=Cluster0

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=greenledger22@gmail.com
spring.mail.password=Green#2000

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


