#spring.application.name=greenledger
server.port=8080
server.address=0.0.0.0
spring.data.mongodb.uri=mongodb+srv://greenledger22_db_user:P5uOJYAEFzQqWCsN@cluster0.od8ro7c.mongodb.net/sustainability?appName=Cluster0