version: '3.8'

services:

  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"

  app:
    image: green-ledger
    container_name: green_ledger_app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://greenledger22_db_user:P5uOJYAEFzQqWCsN@cluster0.od8ro7c.mongodb.net/sustainability?appName=Cluster0